basePath: /
host: localhost:8081
info:
  contact:
    email: contact@esieespace.fr
    name: ESIEESPACE Network
    url: http://esieespace.fr
  license:
    name: GPL-3.0
    url: https://github.com/SpaceRouter/authentication_server/blob/louis/LICENSE
  title: SpaceRouter docker_api
  version: "0.1"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
