server:
  host: 0.0.0.0
  port: 8082
security:
  secret_key: JESUISHYPERFANDESEXE
  auth_server: "http://localhost:8080"

db:
  type: "sqlite"
  database: "gorm.db"
  user: ""
  password: ""
  host: ""
  port: "80"